name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          run: |
            echo "NODE_VERSION=14" >> $GITHUB_ENV
        - name: Use the value
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
