name: npm test two job
on: 
  workflow_dispatch:                  # déclencheur à la main

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'       # long term support
      - name: run test                # un tiré "-" correspond à une step
        shell: bash
        run: |
          npm test
          mpm install