name: npm test
on: 
  workflow_dispatch:                  # déclencheur à la main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install Node.js  
        uses: actions/setup-node@v3 
        with:
          node-version: 'lts/*'        # long term support
      - run: npm ci                    # un tiré "-" correspon à une step
      - run: npm test
  job2:
    needs: job1    